const SUPPORTED_EHRS = [
  { id: "epic", name: "Epic / EpicCare Link", hostPatterns: ["epic.com", "epiccarelink.com"] },
  { id: "athena", name: "athenahealth", hostPatterns: ["athenahealth.com"] },
  { id: "ecw", name: "eClinicalWorks", hostPatterns: ["eclinicalworks.com", "ecwcloud.com"] },
  { id: "practice-fusion", name: "Practice Fusion", hostPatterns: ["practicefusion.com"] },
  { id: "nextgen", name: "NextGen", hostPatterns: ["nextgen.com"] },
  { id: "cerner", name: "Cerner / Oracle Health", hostPatterns: ["cerner.com", "oraclecloud.com"] },
];

function detectEhr(hostname) {
  const normalizedHost = hostname.toLowerCase();
  return (
    SUPPORTED_EHRS.find((ehr) =>
      ehr.hostPatterns.some((pattern) => normalizedHost.includes(pattern)),
    ) ?? null
  );
}

function formatSoapForEhr() {
  return [
    "Patient: Elena Ramirez",
    "DOB: 02/18/1972",
    "Context: Hypertension follow-up",
    "",
    "SUBJECTIVE",
    "Patient reports blood pressure has been better controlled at home and denies chest pain, shortness of breath, dizziness, or medication side effects.",
    "",
    "OBJECTIVE",
    "Alert, oriented, no acute distress. Home BP averages around 128/78 per patient report.",
    "",
    "ASSESSMENT",
    "Hypertension, controlled on current therapy. Medication tolerated without reported side effects.",
    "",
    "PLAN",
    "Continue lisinopril. Repeat BMP. Reinforce low-sodium diet and walking. Follow up in 3 months.",
    "",
    "Suggested E/M/CPT: 99213, G2211",
    "Suggested ICD-10: I10, Z79.899",
    "",
    "Generated by MedGuard AI. Review before signing.",
  ].join("\n");
}

const ehr = detectEhr(window.location.hostname);

function createPushButton() {
  const existingButton = document.getElementById("medguard-ehr-push-button");
  if (existingButton || !ehr) {
    return;
  }

  const button = document.createElement("button");
  button.id = "medguard-ehr-push-button";
  button.type = "button";
  button.textContent = "MedGuard Push";
  button.title = `Push latest MedGuard note into ${ehr.name}`;
  button.addEventListener("click", handlePushClick);
  document.body.appendChild(button);
}

async function getLatestNote() {
  return new Promise((resolve) => {
    chrome.runtime.sendMessage({ type: "MEDGUARD_GET_LATEST_NOTE" }, resolve);
  });
}

async function copyFormattedNote(formatted) {
  if (navigator.clipboard?.writeText) {
    await navigator.clipboard.writeText(formatted);
    return true;
  }

  const textarea = document.createElement("textarea");
  textarea.value = formatted;
  textarea.style.position = "fixed";
  textarea.style.left = "-9999px";
  document.body.appendChild(textarea);
  textarea.select();
  const copied = document.execCommand("copy");
  textarea.remove();
  return copied;
}

function findLikelyEhrTextArea() {
  return (
    document.querySelector("textarea:not([readonly]):not([disabled])") ||
    document.querySelector('[contenteditable="true"]')
  );
}

async function handlePushClick() {
  const button = document.getElementById("medguard-ehr-push-button");
  if (!button) {
    return;
  }

  button.textContent = "Preparing...";

  const response = await getLatestNote();
  const formatted = response?.formatted || formatSoapForEhr();
  const target = findLikelyEhrTextArea();

  if (target instanceof HTMLTextAreaElement) {
    target.value = `${target.value ? `${target.value}\n\n` : ""}${formatted}`;
    target.dispatchEvent(new Event("input", { bubbles: true }));
    button.textContent = "Inserted";
  } else if (target instanceof HTMLElement) {
    target.textContent = `${target.textContent ? `${target.textContent}\n\n` : ""}${formatted}`;
    target.dispatchEvent(new InputEvent("input", { bubbles: true }));
    button.textContent = "Inserted";
  } else {
    await copyFormattedNote(formatted);
    button.textContent = "Copied";
  }

  window.setTimeout(() => {
    button.textContent = "MedGuard Push";
  }, 1800);
}

createPushButton();
