export const MEDGUARD_DEFAULT_APP_URL = "http://localhost:3000";

export const SUPPORTED_EHRS = [
  {
    id: "epic",
    name: "Epic / EpicCare Link",
    hostPatterns: ["epic.com", "epiccarelink.com"],
  },
  {
    id: "athena",
    name: "athenahealth",
    hostPatterns: ["athenahealth.com"],
  },
  {
    id: "ecw",
    name: "eClinicalWorks",
    hostPatterns: ["eclinicalworks.com", "ecwcloud.com"],
  },
  {
    id: "practice-fusion",
    name: "Practice Fusion",
    hostPatterns: ["practicefusion.com"],
  },
  {
    id: "nextgen",
    name: "NextGen",
    hostPatterns: ["nextgen.com"],
  },
  {
    id: "cerner",
    name: "Cerner / Oracle Health",
    hostPatterns: ["cerner.com", "oraclecloud.com"],
  },
];

export const demoPayload = {
  patient: {
    name: "Elena Ramirez",
    dob: "02/18/1972",
    reason: "Hypertension follow-up",
  },
  latestNote: {
    title: "SOAP Note - Hypertension Follow-up",
    subjective:
      "Patient reports blood pressure has been better controlled at home and denies chest pain, shortness of breath, dizziness, or medication side effects.",
    objective:
      "Alert, oriented, no acute distress. Home BP averages around 128/78 per patient report.",
    assessment:
      "Hypertension, controlled on current therapy. Medication tolerated without reported side effects.",
    plan:
      "Continue lisinopril. Repeat BMP. Reinforce low-sodium diet and walking. Follow up in 3 months.",
    billingCodes: ["99213", "G2211"],
    icdCodes: ["I10", "Z79.899"],
  },
};

export function detectEhr(hostname) {
  const normalizedHost = hostname.toLowerCase();

  return (
    SUPPORTED_EHRS.find((ehr) =>
      ehr.hostPatterns.some((pattern) => normalizedHost.includes(pattern)),
    ) ?? null
  );
}

export function formatSoapForEhr(payload = demoPayload) {
  const { patient, latestNote } = payload;

  return [
    `Patient: ${patient.name}`,
    `DOB: ${patient.dob}`,
    `Context: ${patient.reason}`,
    "",
    "SUBJECTIVE",
    latestNote.subjective,
    "",
    "OBJECTIVE",
    latestNote.objective,
    "",
    "ASSESSMENT",
    latestNote.assessment,
    "",
    "PLAN",
    latestNote.plan,
    "",
    `Suggested E/M/CPT: ${latestNote.billingCodes.join(", ")}`,
    `Suggested ICD-10: ${latestNote.icdCodes.join(", ")}`,
    "",
    "Generated by MedGuard AI. Review before signing.",
  ].join("\n");
}
